=== brianlala/SPPeriodicChecks/Script/config.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="AppSettings">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="General">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:boolean" name="Debug"/>
              <xs:element type="xs:unsignedInt" name="RemoteTimeOut"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Credentials">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="UserName"/>
              <xs:element type="xs:string" name="Password"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Email">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:boolean" name="SendReportsViaEmail"/>
              <xs:element type="xs:string" name="SMTPServer"/>
              <xs:element type="xs:string" name="MailFrom"/>
              <xs:element type="xs:string" name="MailTo"/>
              <xs:element type="xs:string" name="MailCC"/>
              <xs:element type="xs:string" name="MailBCC"/>
              <xs:element type="xs:string" name="SubjectSuffix"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Reporting">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:boolean" name="ReportsToDisk"/>
              <xs:element type="xs:string" name="ReportsFolder"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="PatchScan">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="WSUSCabPath"/>
              <xs:element type="xs:boolean" name="DownloadWSUSFile"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Logging">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:string" name="LogPrefix"/>
              <xs:element type="xs:string" name="LogFolder"/>
              <xs:element type="xs:string" name="RemoteLogFolder"/>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="Checks">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="Check" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="Path" minOccurs="0" />
                    <xs:element type="xs:string" name="Filename" minOccurs="0" />
                    <xs:element type="xs:string" name="WMIClass" minOccurs="0" />
                    <xs:element type="xs:unsignedInt" name="MinLUNPaths" minOccurs="0" />
                  </xs:sequence>
                  <xs:attribute name="Id" use="required">
                    <xs:simpleType>
                      <xs:restriction base="xs:integer">
                        <xs:pattern value="31|50"/>
                      </xs:restriction>
                    </xs:simpleType>
                  </xs:attribute>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== brianlala/SPPeriodicChecks/Script/config.xml
<?xml version="1.0" encoding="utf-8" ?>
<AppSettings xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="config.xsd">
    <General>
        <Debug>false</Debug>
        <RemoteTimeOut>21600</RemoteTimeOut>
    </General>
    <Credentials>
        <UserName>acme\adminyk</UserName>
        <Password>abc</Password>
    </Credentials>
    <Email>
        <SendReportsViaEmail>true</SendReportsViaEmail>
        <SMTPServer>smtp.beheer.nl</SMTPServer>
        <MailFrom>sharepoint@beheer.nl</MailFrom>
        <MailTo>sharepoint@beheer.nl</MailTo>
        <MailCC></MailCC>
        <MailBCC></MailBCC>
        <SubjectSuffix></SubjectSuffix>
    </Email>
    <Reporting>
        <ReportsToDisk>false</ReportsToDisk>
        <ReportsFolder>.\Reports</ReportsFolder>
    </Reporting>
    <PatchScan>
        <WSUSCabPath>.</WSUSCabPath>
        <DownloadWSUSFile>false</DownloadWSUSFile>
    </PatchScan>
    <Logging>
        <LogPrefix>PeriodicChecks</LogPrefix>
        <LogFolder>Logs</LogFolder>
        <RemoteLogFolder>C:\Logs</RemoteLogFolder>
    </Logging>
    <Checks>
        <Check Id='31'>
            <Path>C:\Windows\Monitoring</Path>
            <Filename>servicesconfig.txt</Filename>
        </Check>
        <Check Id='50'>
            <WMIClass>HPDSM_PERFINFO</WMIClass>
            <MinLUNPaths>4</MinLUNPaths>
        </Check>
    </Checks>
</AppSettings>
